//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRoutes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryRoutes()
        {
            this.DestinationsRoute = new HashSet<DestinationsRoute>();
        }
    
        public int DeliveryRoutesID { get; set; }
        public int SendingCompanyID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual SendingCompany SendingCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DestinationsRoute> DestinationsRoute { get; set; }
    }
}
