//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationsRoute
    {
        public int DestinationsRouteID { get; set; }
        public int DeliveryRoutesID { get; set; }
        public int OrderID { get; set; }
    
        public virtual DeliveryRoutes DeliveryRoutes { get; set; }
        public virtual Order Order { get; set; }
    }
}
