//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuicklyEntities : DbContext
    {
        public QuicklyEntities()
            : base("name=QuicklyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessDays> BusinessDays { get; set; }
        public virtual DbSet<CarsCampany> CarsCampany { get; set; }
        public virtual DbSet<CarsTypes> CarsTypes { get; set; }
        public virtual DbSet<CitiesCompany> CitiesCompany { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CompanyBankDetails> CompanyBankDetails { get; set; }
        public virtual DbSet<DeliveryRoutes> DeliveryRoutes { get; set; }
        public virtual DbSet<DeliveryType> DeliveryType { get; set; }
        public virtual DbSet<DeliveryUrgency> DeliveryUrgency { get; set; }
        public virtual DbSet<DestinationsRoute> DestinationsRoute { get; set; }
        public virtual DbSet<GivingDelivery> GivingDelivery { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<SendingCompany> SendingCompany { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TakingDelivery> TakingDelivery { get; set; }
    }
}
