//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.DestinationsRoute = new HashSet<DestinationsRoute>();
            this.GivingDelivery = new HashSet<GivingDelivery>();
            this.TakingDelivery = new HashSet<TakingDelivery>();
        }
    
        public int OrderID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int DeliveryTypeID { get; set; }
        public int Amount { get; set; }
        public double Volume { get; set; }
        public int DeliveryUrgencyID { get; set; }
        public double FinalPay { get; set; }
        public string Note { get; set; }
        public bool SentOrNot { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DeliveryType DeliveryType { get; set; }
        public virtual DeliveryUrgency DeliveryUrgency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DestinationsRoute> DestinationsRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GivingDelivery> GivingDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakingDelivery> TakingDelivery { get; set; }
    }
}
