//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakingDelivery
    {
        public int TakingDeliveryID { get; set; }
        public int OrderID { get; set; }
        public int CityID { get; set; }
        public int StreetID { get; set; }
        public Nullable<int> BuildingNumber { get; set; }
        public Nullable<int> EntranceBuilding { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public int ApartmentNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string AdditionalPhone { get; set; }
        public string Email { get; set; }
        public System.TimeSpan PickUpTime { get; set; }
        public System.TimeSpan PickUpTimeUntil { get; set; }
        public Nullable<double> latAddress { get; set; }
        public Nullable<double> lngAddress { get; set; }
        public string NameAddress { get; set; }
    
        public virtual City City { get; set; }
        public virtual Order Order { get; set; }
        public virtual Street Street { get; set; }
    }
}
